services:
  # application
  spring-mvc-resttemplate:
    image: spring-mvc-resttemplate:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=performance
  spring-mvc-webclient:
    image: spring-mvc-webclient:0.0.1-SNAPSHOT
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=performance
  spring-webflux:
    image: spring-webflux:0.0.1-SNAPSHOT
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=performance
  vertx:
    image: vertx:0.0.1-SNAPSHOT
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=performance

  # external-applications
  external1:
    container_name: external1
    image: external:0.0.1-SNAPSHOT
    ports:
      - "9090:9090"
  external2:
    container_name: external2
    image: external:0.0.1-SNAPSHOT
    ports:
      - "9091:9090"
  external3:
    container_name: external3
    image: external:0.0.1-SNAPSHOT
    ports:
      - "9092:9090"
  external4:
    container_name: external4
    image: external:0.0.1-SNAPSHOT
    ports:
      - "9093:9090"
  external5:
    container_name: external5
    image: external:0.0.1-SNAPSHOT
    ports:
      - "9094:9090"
  external6:
    container_name: external6
    image: external:0.0.1-SNAPSHOT
    ports:
      - "9095:9090"
  external7:
    container_name: external7
    image: external:0.0.1-SNAPSHOT
    ports:
      - "9096:9090"
  external8:
    container_name: external8
    image: external:0.0.1-SNAPSHOT
    ports:
      - "9097:9090"
  external9:
    container_name: external9
    image: external:0.0.1-SNAPSHOT
    ports:
      - "9098:9090"
  external10:
    container_name: external10
    image: external:0.0.1-SNAPSHOT
    ports:
      - "9099:9090"