server:
  port: 8080
  tomcat:
    accept-count: 100
    max-connections: 500
    threads:
      max: 500
      min-spare: 200

spring:
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true